$schema: https://json-schema.org/draft/2020-12/schema
description: A three-dimensional spatial region located on or near Earth's surface
type: object
properties:
  type:
    type: string
    const: cco:GeospatialRegion
    x-jsonld-id: '@type'
  id:
    type: string
    x-jsonld-id: '@id'
required:
  - type
x-jsonld-prefixes:
  cco: https://www.commoncoreontologies.org/
