$schema: https://json-schema.org/draft/2020-12/schema
description: Common Core Ontology - Extended Relation module with atomic building
  blocks
$defs:
  Relation:
    $ref: classes/Relation/schema.yaml
  SpatialRelation:
    $ref: classes/SpatialRelation/schema.yaml
anyOf:
- $ref: '#/$defs/Relation'
- $ref: '#/$defs/SpatialRelation'
