$schema: https://json-schema.org/draft/2020-12/schema
description: A set of values that specify position within a coordinate system
type: object
properties:
  type:
    type: string
    const: cco:Coordinates
    x-jsonld-id: '@type'
  id:
    type: string
    x-jsonld-id: '@id'
required:
  - type
x-jsonld-prefixes:
  cco: https://www.commoncoreontologies.org/
