$schema: https://json-schema.org/draft/2020-12/schema
description: Common Core Ontology - Event module with atomic building blocks
$defs:
  Event:
    $ref: classes/Event/schema.yaml
  Act:
    $ref: classes/Act/schema.yaml
  Process:
    $ref: classes/Process/schema.yaml
anyOf:
- $ref: '#/$defs/Event'
- $ref: '#/$defs/Act'
- $ref: '#/$defs/Process'
