$schema: https://json-schema.org/draft/2020-12/schema
description: Information content entity that describes something
type: object
properties:
  type:
    type: string
    const: cco:Description
    x-jsonld-id: '@type'
  id:
    type: string
    x-jsonld-id: '@id'
required:
  - type
x-jsonld-prefixes:
  cco: https://www.commoncoreontologies.org/
