$schema: https://json-schema.org/draft/2020-12/schema
description: Common Core Ontology - Information Entity module with atomic building
  blocks
$defs:
  InformationContentEntity:
    $ref: classes/InformationContentEntity/schema.yaml
  Document:
    $ref: classes/Document/schema.yaml
  Dataset:
    $ref: classes/Dataset/schema.yaml
  Image:
    $ref: classes/Image/schema.yaml
  Text:
    $ref: classes/Text/schema.yaml
  DataFile:
    $ref: classes/DataFile/schema.yaml
  Identifier:
    $ref: classes/Identifier/schema.yaml
  Name:
    $ref: classes/Name/schema.yaml
  Description:
    $ref: classes/Description/schema.yaml
anyOf:
- $ref: '#/$defs/InformationContentEntity'
- $ref: '#/$defs/Document'
- $ref: '#/$defs/Dataset'
- $ref: '#/$defs/Image'
- $ref: '#/$defs/Text'
- $ref: '#/$defs/DataFile'
- $ref: '#/$defs/Identifier'
- $ref: '#/$defs/Name'
- $ref: '#/$defs/Description'
